site_name: quasitools

theme: 'readthedocs'
copyright: "Copyright Government of Canada 2017-2018"

site_dir: 'public'

nav:
    - Home: index.md
    - Requirements: requirements.md
    - Installation: installation.md
    - Tools:
        - complexity: complexity.md
        - distance: distance.md
        - quality: quality.md
    - Contact: contact.md
    - Legal: legal.md
